// Generated by the protocol buffer compiler.  DO NOT EDIT!
/*
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "robotdata.pb.h"

#include <algorithm>

#include "../Network/protobuf/stubs/once.h"
#include "../Network/protobuf/io/coded_stream.h"
#include "../Network/protobuf/wire_format_lite_inl.h"
// @@protoc_insertion_point(includes)

namespace data {

void protobuf_ShutdownFile_robotdata_2eproto() {
  delete DataMessage::default_instance_;
  delete DataMessage_IndexToTypeMapMessage::default_instance_;
  delete DataMessage_IndexToValueMapMessage::default_instance_;
  delete CompleteMessage::default_instance_;
}

void protobuf_AddDesc_robotdata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  DataMessage::default_instance_ = new DataMessage();
  DataMessage_IndexToTypeMapMessage::default_instance_ = new DataMessage_IndexToTypeMapMessage();
  DataMessage_IndexToValueMapMessage::default_instance_ = new DataMessage_IndexToValueMapMessage();
  CompleteMessage::default_instance_ = new CompleteMessage();
  DataMessage::default_instance_->InitAsDefaultInstance();
  DataMessage_IndexToTypeMapMessage::default_instance_->InitAsDefaultInstance();
  DataMessage_IndexToValueMapMessage::default_instance_->InitAsDefaultInstance();
  CompleteMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_robotdata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_robotdata_2eproto {
  StaticDescriptorInitializer_robotdata_2eproto() {
    protobuf_AddDesc_robotdata_2eproto();
  }
} static_descriptor_initializer_robotdata_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int DataMessage_IndexToTypeMapMessage::kTypeFieldNumber;
#endif  // !_MSC_VER

DataMessage_IndexToTypeMapMessage::DataMessage_IndexToTypeMapMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void DataMessage_IndexToTypeMapMessage::InitAsDefaultInstance() {
}

DataMessage_IndexToTypeMapMessage::DataMessage_IndexToTypeMapMessage(const DataMessage_IndexToTypeMapMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void DataMessage_IndexToTypeMapMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DataMessage_IndexToTypeMapMessage::~DataMessage_IndexToTypeMapMessage() {
  SharedDtor();
}

void DataMessage_IndexToTypeMapMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DataMessage_IndexToTypeMapMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const DataMessage_IndexToTypeMapMessage& DataMessage_IndexToTypeMapMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robotdata_2eproto();  return *default_instance_;
}

DataMessage_IndexToTypeMapMessage* DataMessage_IndexToTypeMapMessage::default_instance_ = NULL;

DataMessage_IndexToTypeMapMessage* DataMessage_IndexToTypeMapMessage::New() const {
  return new DataMessage_IndexToTypeMapMessage;
}

void DataMessage_IndexToTypeMapMessage::Clear() {
  type_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool DataMessage_IndexToTypeMapMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_type()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_type;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DataMessage_IndexToTypeMapMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string type = 1;
  for (int i = 0; i < this->type_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->type(i), output);
  }
  
}

int DataMessage_IndexToTypeMapMessage::ByteSize() const {
  int total_size = 0;
  
  // repeated string type = 1;
  total_size += 1 * this->type_size();
  for (int i = 0; i < this->type_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->type(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DataMessage_IndexToTypeMapMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DataMessage_IndexToTypeMapMessage*>(&from));
}

void DataMessage_IndexToTypeMapMessage::MergeFrom(const DataMessage_IndexToTypeMapMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  type_.MergeFrom(from.type_);
}

void DataMessage_IndexToTypeMapMessage::CopyFrom(const DataMessage_IndexToTypeMapMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataMessage_IndexToTypeMapMessage::IsInitialized() const {
  
  return true;
}

void DataMessage_IndexToTypeMapMessage::Swap(DataMessage_IndexToTypeMapMessage* other) {
  if (other != this) {
    type_.Swap(&other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string DataMessage_IndexToTypeMapMessage::GetTypeName() const {
  return "data.DataMessage.IndexToTypeMapMessage";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DataMessage_IndexToValueMapMessage::kValueFieldNumber;
#endif  // !_MSC_VER

DataMessage_IndexToValueMapMessage::DataMessage_IndexToValueMapMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void DataMessage_IndexToValueMapMessage::InitAsDefaultInstance() {
}

DataMessage_IndexToValueMapMessage::DataMessage_IndexToValueMapMessage(const DataMessage_IndexToValueMapMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void DataMessage_IndexToValueMapMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DataMessage_IndexToValueMapMessage::~DataMessage_IndexToValueMapMessage() {
  SharedDtor();
}

void DataMessage_IndexToValueMapMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DataMessage_IndexToValueMapMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const DataMessage_IndexToValueMapMessage& DataMessage_IndexToValueMapMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robotdata_2eproto();  return *default_instance_;
}

DataMessage_IndexToValueMapMessage* DataMessage_IndexToValueMapMessage::default_instance_ = NULL;

DataMessage_IndexToValueMapMessage* DataMessage_IndexToValueMapMessage::New() const {
  return new DataMessage_IndexToValueMapMessage;
}

void DataMessage_IndexToValueMapMessage::Clear() {
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool DataMessage_IndexToValueMapMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string value = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_value;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DataMessage_IndexToValueMapMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string value = 1;
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->value(i), output);
  }
  
}

int DataMessage_IndexToValueMapMessage::ByteSize() const {
  int total_size = 0;
  
  // repeated string value = 1;
  total_size += 1 * this->value_size();
  for (int i = 0; i < this->value_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->value(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DataMessage_IndexToValueMapMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DataMessage_IndexToValueMapMessage*>(&from));
}

void DataMessage_IndexToValueMapMessage::MergeFrom(const DataMessage_IndexToValueMapMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_.MergeFrom(from.value_);
}

void DataMessage_IndexToValueMapMessage::CopyFrom(const DataMessage_IndexToValueMapMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataMessage_IndexToValueMapMessage::IsInitialized() const {
  
  return true;
}

void DataMessage_IndexToValueMapMessage::Swap(DataMessage_IndexToValueMapMessage* other) {
  if (other != this) {
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string DataMessage_IndexToValueMapMessage::GetTypeName() const {
  return "data.DataMessage.IndexToValueMapMessage";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int DataMessage::kClassNameFieldNumber;
const int DataMessage::kIndexToTypeMapFieldNumber;
const int DataMessage::kIndexToValueMapFieldNumber;
#endif  // !_MSC_VER

DataMessage::DataMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void DataMessage::InitAsDefaultInstance() {
  indextotypemap_ = const_cast< ::data::DataMessage_IndexToTypeMapMessage*>(&::data::DataMessage_IndexToTypeMapMessage::default_instance());
  indextovaluemap_ = const_cast< ::data::DataMessage_IndexToValueMapMessage*>(&::data::DataMessage_IndexToValueMapMessage::default_instance());
}

DataMessage::DataMessage(const DataMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void DataMessage::SharedCtor() {
  _cached_size_ = 0;
  classname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  indextotypemap_ = NULL;
  indextovaluemap_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DataMessage::~DataMessage() {
  SharedDtor();
}

void DataMessage::SharedDtor() {
  if (classname_ != &::google::protobuf::internal::kEmptyString) {
    delete classname_;
  }
  if (this != default_instance_) {
    delete indextotypemap_;
    delete indextovaluemap_;
  }
}

void DataMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const DataMessage& DataMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robotdata_2eproto();  return *default_instance_;
}

DataMessage* DataMessage::default_instance_ = NULL;

DataMessage* DataMessage::New() const {
  return new DataMessage;
}

void DataMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_classname()) {
      if (classname_ != &::google::protobuf::internal::kEmptyString) {
        classname_->clear();
      }
    }
    if (has_indextotypemap()) {
      if (indextotypemap_ != NULL) indextotypemap_->::data::DataMessage_IndexToTypeMapMessage::Clear();
    }
    if (has_indextovaluemap()) {
      if (indextovaluemap_ != NULL) indextovaluemap_->::data::DataMessage_IndexToValueMapMessage::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool DataMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string ClassName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_classname()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_IndexToTypeMap;
        break;
      }
      
      // required .data.DataMessage.IndexToTypeMapMessage IndexToTypeMap = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_IndexToTypeMap:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_indextotypemap()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_IndexToValueMap;
        break;
      }
      
      // required .data.DataMessage.IndexToValueMapMessage IndexToValueMap = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_IndexToValueMap:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_indextovaluemap()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DataMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string ClassName = 1;
  if (has_classname()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->classname(), output);
  }
  
  // required .data.DataMessage.IndexToTypeMapMessage IndexToTypeMap = 2;
  if (has_indextotypemap()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->indextotypemap(), output);
  }
  
  // required .data.DataMessage.IndexToValueMapMessage IndexToValueMap = 3;
  if (has_indextovaluemap()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->indextovaluemap(), output);
  }
  
}

int DataMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string ClassName = 1;
    if (has_classname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->classname());
    }
    
    // required .data.DataMessage.IndexToTypeMapMessage IndexToTypeMap = 2;
    if (has_indextotypemap()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->indextotypemap());
    }
    
    // required .data.DataMessage.IndexToValueMapMessage IndexToValueMap = 3;
    if (has_indextovaluemap()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->indextovaluemap());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DataMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const DataMessage*>(&from));
}

void DataMessage::MergeFrom(const DataMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_classname()) {
      set_classname(from.classname());
    }
    if (from.has_indextotypemap()) {
      mutable_indextotypemap()->::data::DataMessage_IndexToTypeMapMessage::MergeFrom(from.indextotypemap());
    }
    if (from.has_indextovaluemap()) {
      mutable_indextovaluemap()->::data::DataMessage_IndexToValueMapMessage::MergeFrom(from.indextovaluemap());
    }
  }
}

void DataMessage::CopyFrom(const DataMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void DataMessage::Swap(DataMessage* other) {
  if (other != this) {
    std::swap(classname_, other->classname_);
    std::swap(indextotypemap_, other->indextotypemap_);
    std::swap(indextovaluemap_, other->indextovaluemap_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string DataMessage::GetTypeName() const {
  return "data.DataMessage";
}


// ===================================================================

#ifndef _MSC_VER
const int CompleteMessage::kDataFieldNumber;
#endif  // !_MSC_VER

CompleteMessage::CompleteMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void CompleteMessage::InitAsDefaultInstance() {
}

CompleteMessage::CompleteMessage(const CompleteMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void CompleteMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompleteMessage::~CompleteMessage() {
  SharedDtor();
}

void CompleteMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CompleteMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CompleteMessage& CompleteMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robotdata_2eproto();  return *default_instance_;
}

CompleteMessage* CompleteMessage::default_instance_ = NULL;

CompleteMessage* CompleteMessage::New() const {
  return new CompleteMessage;
}

void CompleteMessage::Clear() {
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool CompleteMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .data.DataMessage Data = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_Data;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompleteMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .data.DataMessage Data = 1;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->data(i), output);
  }
  
}

int CompleteMessage::ByteSize() const {
  int total_size = 0;
  
  // repeated .data.DataMessage Data = 1;
  total_size += 1 * this->data_size();
  for (int i = 0; i < this->data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompleteMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CompleteMessage*>(&from));
}

void CompleteMessage::MergeFrom(const CompleteMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  data_.MergeFrom(from.data_);
}

void CompleteMessage::CopyFrom(const CompleteMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompleteMessage::IsInitialized() const {
  
  for (int i = 0; i < data_size(); i++) {
    if (!this->data(i).IsInitialized()) return false;
  }
  return true;
}

void CompleteMessage::Swap(CompleteMessage* other) {
  if (other != this) {
    data_.Swap(&other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string CompleteMessage::GetTypeName() const {
  return "data.CompleteMessage";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace data

// @@protoc_insertion_point(global_scope)
*/
